# Name of the workflow
name: Check Merge Conflicts and Create Pull Request  

# Define the event trigger for the workflow
on:
  push:
    branches:
      - '*'  # Trigger the workflow for all branches

# Define jobs for the workflow
jobs:
  # Define the job to create a pull request
  create-pull-request:
    # Use an Ubuntu runner for this job
    runs-on: ubuntu-latest  

    # Steps for the job
    steps:
      # Step to create a pull request
      - name: Create Pull Request  
        # ID for this step
        id: create_pr  

        # Script to run for the step
        run: |
          # Use the GitHub CLI to create a pull request
          gh pr create \
            # Set the title of the pull request
            --title "${{ github.ref }} -> main" \
            # Set the commit message for the pull request
            --body "Automated pull request creation from ${{ github.ref }} branch." \
            # Specify the reviewer for the pull request
            --reviewer "reviewer_username" \
            # Specify the base branch for the pull request
            --base "main" \
            # Specify the head branch for the pull request
            --head "${{ github.ref }}" \
            # Specify the repository where the pull request will be created
            --repo "${{ github.repository }}" \
            # Provide the GitHub token for authentication
            --token "${{ secrets.GH_TOKEN }}"

          # Check if the pull request creation was successful
          if [ $? -ne 0 ]; then
            # Notifies the user if pull request creation failed
            echo "::error::Failed to create pull request. Please check the workflow logs for details."
            # Exit the script
            exit 1
          fi
