# Name of the workflow
name: Check Merge Conflicts and Create Pull Request  

# Define the event trigger for the workflow
on:
  push:
    branches:
      - '*'  # Trigger the workflow for all branches

# Define jobs for the workflow
jobs:
  # Define the job to create a pull request
  create-pull-request:
    # Use an Ubuntu runner for this job
    runs-on: ubuntu-latest  

    # Steps for the job
    steps:
      # Step to create a pull request
      - name: Create Pull Request  
        # ID for this step
        id: create_pr  

        # Script to run for the step
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Set the GH_TOKEN environment variable with the GitHub token

        run: |
          # Use the GitHub CLI to create a pull request
          gh pr create \
            --title "${{ github.ref }} -> main" \
            --body "Automated pull request creation from ${{ github.ref }} branch." \
            --reviewer "dheeraj1228" \
            --base "main" \
            --head "${{ github.ref }}" \
            --repo "${{ github.repository }}"
